# Generated by Django 2.0.7 on 2018-08-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180810_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadmessagecounter',
            name='user',
        ),
        migrations.DeleteModel(
            name='UnreadMessageCounter',
        ),
    ]
