# Generated by Django 2.0.7 on 2018-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180810_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='readed',
        ),
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='has read'),
        ),
    ]
