# Generated by Django 2.0.7 on 2018-07-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180721_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='date_modified',
        ),
    ]
