# Generated by Django 2.0.7 on 2018-07-21 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_bloguser_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified'),
        ),
    ]
