# Generated by Django 2.0.7 on 2018-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bloguser_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The email address is already occupied'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
