# Generated by Django 2.0.7 on 2018-07-23 08:27

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180722_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and -/_ only.', max_length=150, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
