# Generated by Django 2.0.7 on 2018-07-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180723_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'The email address is already occupied'}, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
