# Generated by Django 2.0.7 on 2018-07-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20180727_2245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='body')),
                ('created_time', models.DateField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', models.DateField(auto_now=True, verbose_name='last modified time')),
                ('visiable', models.BooleanField(verbose_name='visiable')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='commented post')),
                ('superior', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comments.Comment', verbose_name='superior comment')),
            ],
            options={
                'get_latest_by': 'created_time',
                'verbose_name_plural': 'comments',
                'verbose_name': 'comment',
                'ordering': ['-created_time'],
            },
        ),
    ]
