# Generated by Django 2.0.7 on 2018-07-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180727_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='visiable',
            field=models.BooleanField(default=True, verbose_name='visiable'),
        ),
    ]
