# Generated by Django 2.0.7 on 2018-07-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180728_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified time'),
        ),
    ]
