# Generated by Django 2.0.7 on 2018-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='created time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateField(auto_now=True, verbose_name='last modified time'),
        ),
    ]
