# Generated by Django 2.0.7 on 2018-07-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthuser',
            name='client_id',
        ),
        migrations.AddField(
            model_name='oauthuser',
            name='userid',
            field=models.CharField(default=123456, max_length=50, verbose_name='user id'),
            preserve_default=False,
        ),
    ]
