# Generated by Django 2.0.7 on 2018-07-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20180724_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthuser',
            options={'verbose_name': 'OAuth Users'},
        ),
    ]
